# spotify/app.yaml

capability:
    - audio
    - display
    - localtime

volume:
    /etc/localtime:
        readonly: True

    /home/spotify/.config/spotify:
        host: ${HOME}/.config/spotify

option:
    detach: True

