# spotify/app.yaml

capability:
    audio: {}
    display: {}

volume:
    /etc/localtime:
        readonly: True

    /home/spotify/.spotify:
        host: ${HOME}/.spotify

option:
    detach: True

