# spotify/app.yaml

capability:
    - audio
    - display
    - localtime

volume:
    /etc/localtime:
        readonly: True

    /home/user/.config/spotify:
        host: ${HOME}/.config/spotify

    /home/user/.cache/spotify:
        host: ${HOME}/.cache/spotify

option:
    detach: True

